//
//  Food.swift
//  TimeCraft
//
//  Created by Akhilesh Warty on 2024-08-07.
//

import Foundation

struct Nutritent : Codable{
    let nutrientId : Int
    let nutrientName : String
    let unitName : String
    let value : Double
    let rank : Int
    let foodNutrientId : Int
}

struct Food : Codable{
    let fdcId : Int
    let ingredients : String
    let description : String
    let foodCategory : String
    let score : Double
    let packageWeight : String
    let servingSizeUnit : String
    let servingSize : Double
    let householdServingFullText : String
    let foodNutrients : [Nutritent]
}

struct FoodRequest : Codable {
    let totalHits : Int
    let foods : [Food]
}



//{
//    "fdcId": 174626,
//    "description": "Cereals, QUAKER, Oat Bran, QUAKER/MOTHER'S Oat Bran, dry",
//    "commonNames": "",
//    "additionalDescriptions": "",
//    "dataType": "SR Legacy",
//    "ndbNumber": 8231,
//    "publishedDate": "2019-04-01",
//    "foodCategory": "Breakfast Cereals",
//    "allHighlightFields": "",
//    "score": 746.50183,
//    "microbes": [],
//    "foodNutrients": [
//        {
//            "nutrientId": 1051,
//            "nutrientName": "Water",
//            "nutrientNumber": "255",
//            "unitName": "G",
//            "derivationCode": "MC",
//            "derivationDescription": "Manufacturer supplied; Calculated by manufacturer or unknown if analytical or calculated",
//            "derivationId": 47,
//            "value": 8.9,
//            "foodNutrientSourceId": 7,
//            "foodNutrientSourceCode": "9",
//            "foodNutrientSourceDescription": "Calculated by manufacturer, not adjusted or rounded for NLEA",
//            "rank": 100,
//            "indentLevel": 1,
//            "foodNutrientId": 1874057,
//            "dataPoints": 0
//        },
//        {
//            "nutrientId": 1004,
//            "nutrientName": "Total lipid (fat)",
//            "nutrientNumber": "204",
//            "unitName": "G",
//            "derivationCode": "MC",
//            "derivationDescription": "Manufacturer supplied; Calculated by manufacturer or unknown if analytical or calculated",
//            "derivationId": 47,
//            "value": 7.97,
//            "foodNutrientSourceId": 7,
//            "foodNutrientSourceCode": "9",
//            "foodNutrientSourceDescription": "Calculated by manufacturer, not adjusted or rounded for NLEA",
//            "rank": 800,
//            "indentLevel": 1,
//            "foodNutrientId": 1874058,
//            "dataPoints": 0
//        },
//        {
//            "nutrientId": 1087,
//            "nutrientName": "Calcium, Ca",
//            "nutrientNumber": "301",
//            "unitName": "MG",
//            "derivationCode": "MC",
//            "derivationDescription": "Manufacturer supplied; Calculated by manufacturer or unknown if analytical or calculated",
//            "derivationId": 47,
//            "value": 79.0,
//            "foodNutrientSourceId": 7,
//            "foodNutrientSourceCode": "9",
//            "foodNutrientSourceDescription": "Calculated by manufacturer, not adjusted or rounded for NLEA",
//            "rank": 5300,
//            "indentLevel": 1,
//            "foodNutrientId": 1874059,
//            "dataPoints": 0
//        },
//        {
//            "nutrientId": 1095,
//            "nutrientName": "Zinc, Zn",
//            "nutrientNumber": "309",
//            "unitName": "MG",
//            "derivationCode": "MC",
//            "derivationDescription": "Manufacturer supplied; Calculated by manufacturer or unknown if analytical or calculated",
//            "derivationId": 47,
//            "value": 4.2,
//            "foodNutrientSourceId": 7,
//            "foodNutrientSourceCode": "9",
//            "foodNutrientSourceDescription": "Calculated by manufacturer, not adjusted or rounded for NLEA",
//            "rank": 5900,
//            "indentLevel": 1,
//            "foodNutrientId": 1874060,
//            "dataPoints": 0
//        },
//        {
//            "nutrientId": 1167,
//            "nutrientName": "Niacin",
//            "nutrientNumber": "406",
//            "unitName": "MG",
//            "derivationCode": "MC",
//            "derivationDescription": "Manufacturer supplied; Calculated by manufacturer or unknown if analytical or calculated",
//            "derivationId": 47,
//            "value": 0.8,
//            "foodNutrientSourceId": 7,
//            "foodNutrientSourceCode": "9",
//            "foodNutrientSourceDescription": "Calculated by manufacturer, not adjusted or rounded for NLEA",
//            "rank": 6600,
//            "indentLevel": 1,
//            "foodNutrientId": 1874061,
//            "dataPoints": 0
//        },
//        {
//            "nutrientId": 1170,
//            "nutrientName": "Pantothenic acid",
//            "nutrientNumber": "410",
//            "unitName": "MG",
//            "derivationCode": "MC",
//            "derivationDescription": "Manufacturer supplied; Calculated by manufacturer or unknown if analytical or calculated",
//            "derivationId": 47,
//            "value": 0.85,
//            "foodNutrientSourceId": 7,
//            "foodNutrientSourceCode": "9",
//            "foodNutrientSourceDescription": "Calculated by manufacturer, not adjusted or rounded for NLEA",
//            "rank": 6700,
//            "indentLevel": 1,
//            "foodNutrientId": 1874062,
//            "dataPoints": 0
//        },
//        {
//            "nutrientId": 1175,
//            "nutrientName": "Vitamin B-6",
//            "nutrientNumber": "415",
//            "unitName": "MG",
//            "derivationCode": "MC",
//            "derivationDescription": "Manufacturer supplied; Calculated by manufacturer or unknown if analytical or calculated",
//            "derivationId": 47,
//            "value": 0.11,
//            "foodNutrientSourceId": 7,
//            "foodNutrientSourceCode": "9",
//            "foodNutrientSourceDescription": "Calculated by manufacturer, not adjusted or rounded for NLEA",
//            "rank": 6800,
//            "indentLevel": 1,
//            "foodNutrientId": 1874063,
//            "dataPoints": 0
//        },
//        {
//            "nutrientId": 1292,
//            "nutrientName": "Fatty acids, total monounsaturated",
//            "nutrientNumber": "645",
//            "unitName": "G",
//            "derivationCode": "MC",
//            "derivationDescription": "Manufacturer supplied; Calculated by manufacturer or unknown if analytical or calculated",
//            "derivationId": 47,
//            "value": 2.61,
//            "foodNutrientSourceId": 7,
//            "foodNutrientSourceCode": "9",
//            "foodNutrientSourceDescription": "Calculated by manufacturer, not adjusted or rounded for NLEA",
//            "rank": 11400,
//            "indentLevel": 1,
//            "foodNutrientId": 1874064,
//            "dataPoints": 0
//        },
//        {
//            "nutrientId": 1293,
//            "nutrientName": "Fatty acids, total polyunsaturated",
//            "nutrientNumber": "646",
//            "unitName": "G",
//            "derivationCode": "MC",
//            "derivationDescription": "Manufacturer supplied; Calculated by manufacturer or unknown if analytical or calculated",
//            "derivationId": 47,
//            "value": 3.03,
//            "foodNutrientSourceId": 7,
//            "foodNutrientSourceCode": "9",
//            "foodNutrientSourceDescription": "Calculated by manufacturer, not adjusted or rounded for NLEA",
//            "rank": 12900,
//            "indentLevel": 1,
//            "foodNutrientId": 1874065,
//            "dataPoints": 0
//        },
//        {
//            "nutrientId": 1089,
//            "nutrientName": "Iron, Fe",
//            "nutrientNumber": "303",
//            "unitName": "MG",
//            "derivationCode": "MC",
//            "derivationDescription": "Manufacturer supplied; Calculated by manufacturer or unknown if analytical or calculated",
//            "derivationId": 47,
//            "value": 8.07,
//            "foodNutrientSourceId": 7,
//            "foodNutrientSourceCode": "9",
//            "foodNutrientSourceDescription": "Calculated by manufacturer, not adjusted or rounded for NLEA",
//            "rank": 5400,
//            "indentLevel": 1,
//            "foodNutrientId": 1874066,
//            "dataPoints": 0
//        },
//        {
//            "nutrientId": 1098,
//            "nutrientName": "Copper, Cu",
//            "nutrientNumber": "312",
//            "unitName": "MG",
//            "derivationCode": "MC",
//            "derivationDescription": "Manufacturer supplied; Calculated by manufacturer or unknown if analytical or calculated",
//            "derivationId": 47,
//            "value": 0.3,
//            "foodNutrientSourceId": 7,
//            "foodNutrientSourceCode": "9",
//            "foodNutrientSourceDescription": "Calculated by manufacturer, not adjusted or rounded for NLEA",
//            "rank": 6000,
//            "indentLevel": 1,
//            "foodNutrientId": 1874067,
//            "dataPoints": 0
//        },
//        {
//            "nutrientId": 1101,
//            "nutrientName": "Manganese, Mn",
//            "nutrientNumber": "315",
//            "unitName": "MG",
//            "derivationCode": "MC",
//            "derivationDescription": "Manufacturer supplied; Calculated by manufacturer or unknown if analytical or calculated",
//            "derivationId": 47,
//            "value": 5.7,
//            "foodNutrientSourceId": 7,
//            "foodNutrientSourceCode": "9",
//            "foodNutrientSourceDescription": "Calculated by manufacturer, not adjusted or rounded for NLEA",
//            "rank": 6100,
//            "indentLevel": 1,
//            "foodNutrientId": 1874068,
//            "dataPoints": 0
//        },
//        {
//            "nutrientId": 1104,
//            "nutrientName": "Vitamin A, IU",
//            "nutrientNumber": "318",
//            "unitName": "IU",
//            "derivationCode": "MC",
//            "derivationDescription": "Manufacturer supplied; Calculated by manufacturer or unknown if analytical or calculated",
//            "derivationId": 47,
//            "value": 100,
//            "foodNutrientSourceId": 7,
//            "foodNutrientSourceCode": "9",
//            "foodNutrientSourceDescription": "Calculated by manufacturer, not adjusted or rounded for NLEA",
//            "rank": 7500,
//            "indentLevel": 1,
//            "foodNutrientId": 1874069,
//            "dataPoints": 0
//        },
//        {
//            "nutrientId": 1162,
//            "nutrientName": "Vitamin C, total ascorbic acid",
//            "nutrientNumber": "401",
//            "unitName": "MG",
//            "derivationCode": "MC",
//            "derivationDescription": "Manufacturer supplied; Calculated by manufacturer or unknown if analytical or calculated",
//            "derivationId": 47,
//            "value": 0.0,
//            "foodNutrientSourceId": 7,
//            "foodNutrientSourceCode": "9",
//            "foodNutrientSourceDescription": "Calculated by manufacturer, not adjusted or rounded for NLEA",
//            "rank": 6300,
//            "indentLevel": 1,
//            "foodNutrientId": 1874070,
//            "dataPoints": 0
//        },
//        {
//            "nutrientId": 1165,
//            "nutrientName": "Thiamin",
//            "nutrientNumber": "404",
//            "unitName": "MG",
//            "derivationCode": "MC",
//            "derivationDescription": "Manufacturer supplied; Calculated by manufacturer or unknown if analytical or calculated",
//            "derivationId": 47,
//            "value": 0.97,
//            "foodNutrientSourceId": 7,
//            "foodNutrientSourceCode": "9",
//            "foodNutrientSourceDescription": "Calculated by manufacturer, not adjusted or rounded for NLEA",
//            "rank": 6400,
//            "indentLevel": 1,
//            "foodNutrientId": 1874071,
//            "dataPoints": 0
//        },
//        {
//            "nutrientId": 1166,
//            "nutrientName": "Riboflavin",
//            "nutrientNumber": "405",
//            "unitName": "MG",
//            "derivationCode": "MC",
//            "derivationDescription": "Manufacturer supplied; Calculated by manufacturer or unknown if analytical or calculated",
//            "derivationId": 47,
//            "value": 0.3,
//            "foodNutrientSourceId": 7,
//            "foodNutrientSourceCode": "9",
//            "foodNutrientSourceDescription": "Calculated by manufacturer, not adjusted or rounded for NLEA",
//            "rank": 6500,
//            "indentLevel": 1,
//            "foodNutrientId": 1874072,
//            "dataPoints": 0
//        },
//        {
//            "nutrientId": 1007,
//            "nutrientName": "Ash",
//            "nutrientNumber": "207",
//            "unitName": "G",
//            "derivationCode": "MC",
//            "derivationDescription": "Manufacturer supplied; Calculated by manufacturer or unknown if analytical or calculated",
//            "derivationId": 47,
//            "value": 3.14,
//            "foodNutrientSourceId": 7,
//            "foodNutrientSourceCode": "9",
//            "foodNutrientSourceDescription": "Calculated by manufacturer, not adjusted or rounded for NLEA",
//            "rank": 1000,
//            "indentLevel": 1,
//            "foodNutrientId": 1874073,
//            "dataPoints": 0
//        },
//        {
//            "nutrientId": 1018,
//            "nutrientName": "Alcohol, ethyl",
//            "nutrientNumber": "221",
//            "unitName": "G",
//            "derivationCode": "Z",
//            "derivationDescription": "Assumed zero (Insignificant amount or not naturally occurring in a food, such as fiber in meat)",
//            "derivationId": 68,
//            "value": 0.0,
//            "foodNutrientSourceId": 5,
//            "foodNutrientSourceCode": "7",
//            "foodNutrientSourceDescription": "Assumed zero",
//            "rank": 18200,
//            "indentLevel": 1,
//            "foodNutrientId": 1874074,
//            "dataPoints": 0
//        },
//        {
//            "nutrientId": 1178,
//            "nutrientName": "Vitamin B-12",
//            "nutrientNumber": "418",
//            "unitName": "UG",
//            "derivationCode": "MC",
//            "derivationDescription": "Manufacturer supplied; Calculated by manufacturer or unknown if analytical or calculated",
//            "derivationId": 47,
//            "value": 0.0,
//            "foodNutrientSourceId": 7,
//            "foodNutrientSourceCode": "9",
//            "foodNutrientSourceDescription": "Calculated by manufacturer, not adjusted or rounded for NLEA",
//            "rank": 7300,
//            "indentLevel": 1,
//            "foodNutrientId": 1874075,
//            "dataPoints": 0
//        },
//        {
//            "nutrientId": 1253,
//            "nutrientName": "Cholesterol",
//            "nutrientNumber": "601",
//            "unitName": "MG",
//            "derivationCode": "MC",
//            "derivationDescription": "Manufacturer supplied; Calculated by manufacturer or unknown if analytical or calculated",
//            "derivationId": 47,
//            "value": 0.0,
//            "foodNutrientSourceId": 7,
//            "foodNutrientSourceCode": "9",
//            "foodNutrientSourceDescription": "Calculated by manufacturer, not adjusted or rounded for NLEA",
//            "rank": 15700,
//            "indentLevel": 1,
//            "foodNutrientId": 1874076,
//            "dataPoints": 0
//        },
//        {
//            "nutrientId": 1258,
//            "nutrientName": "Fatty acids, total saturated",
//            "nutrientNumber": "606",
//            "unitName": "G",
//            "derivationCode": "MC",
//            "derivationDescription": "Manufacturer supplied; Calculated by manufacturer or unknown if analytical or calculated",
//            "derivationId": 47,
//            "value": 1.43,
//            "foodNutrientSourceId": 7,
//            "foodNutrientSourceCode": "9",
//            "foodNutrientSourceDescription": "Calculated by manufacturer, not adjusted or rounded for NLEA",
//            "rank": 9700,
//            "indentLevel": 1,
//            "foodNutrientId": 1874077,
//            "dataPoints": 0
//        },
//        {
//            "nutrientId": 1008,
//            "nutrientName": "Energy",
//            "nutrientNumber": "208",
//            "unitName": "KCAL",
//            "derivationCode": "MC",
//            "derivationDescription": "Manufacturer supplied; Calculated by manufacturer or unknown if analytical or calculated",
//            "derivationId": 47,
//            "value": 364,
//            "foodNutrientSourceId": 7,
//            "foodNutrientSourceCode": "9",
//            "foodNutrientSourceDescription": "Calculated by manufacturer, not adjusted or rounded for NLEA",
//            "rank": 300,
//            "indentLevel": 1,
//            "foodNutrientId": 1874078,
//            "dataPoints": 0
//        },
//        {
//            "nutrientId": 1103,
//            "nutrientName": "Selenium, Se",
//            "nutrientNumber": "317",
//            "unitName": "UG",
//            "derivationCode": "MC",
//            "derivationDescription": "Manufacturer supplied; Calculated by manufacturer or unknown if analytical or calculated",
//            "derivationId": 47,
//            "value": 0.0,
//            "foodNutrientSourceId": 7,
//            "foodNutrientSourceCode": "9",
//            "foodNutrientSourceDescription": "Calculated by manufacturer, not adjusted or rounded for NLEA",
//            "rank": 6200,
//            "indentLevel": 1,
//            "foodNutrientId": 1874079,
//            "dataPoints": 0
//        },
//        {
//            "nutrientId": 1092,
//            "nutrientName": "Potassium, K",
//            "nutrientNumber": "306",
//            "unitName": "MG",
//            "derivationCode": "MC",
//            "derivationDescription": "Manufacturer supplied; Calculated by manufacturer or unknown if analytical or calculated",
//            "derivationId": 47,
//            "value": 579,
//            "foodNutrientSourceId": 7,
//            "foodNutrientSourceCode": "9",
//            "foodNutrientSourceDescription": "Calculated by manufacturer, not adjusted or rounded for NLEA",
//            "rank": 5700,
//            "indentLevel": 1,
//            "foodNutrientId": 1874080,
//            "dataPoints": 0
//        },
//        {
//            "nutrientId": 2000,
//            "nutrientName": "Total Sugars",
//            "nutrientNumber": "269",
//            "unitName": "G",
//            "derivationCode": "MC",
//            "derivationDescription": "Manufacturer supplied; Calculated by manufacturer or unknown if analytical or calculated",
//            "derivationId": 47,
//            "value": 1.43,
//            "foodNutrientSourceId": 7,
//            "foodNutrientSourceCode": "9",
//            "foodNutrientSourceDescription": "Calculated by manufacturer, not adjusted or rounded for NLEA",
//            "rank": 1510,
//            "indentLevel": 3,
//            "foodNutrientId": 1874081,
//            "dataPoints": 0
//        },
//        {
//            "nutrientId": 1177,
//            "nutrientName": "Folate, total",
//            "nutrientNumber": "417",
//            "unitName": "UG",
//            "derivationCode": "MC",
//            "derivationDescription": "Manufacturer supplied; Calculated by manufacturer or unknown if analytical or calculated",
//            "derivationId": 47,
//            "value": 38.0,
//            "foodNutrientSourceId": 7,
//            "foodNutrientSourceCode": "9",
//            "foodNutrientSourceDescription": "Calculated by manufacturer, not adjusted or rounded for NLEA",
//            "rank": 6900,
//            "indentLevel": 1,
//            "foodNutrientId": 1874082,
//            "dataPoints": 0
//        },
//        {
//            "nutrientId": 1090,
//            "nutrientName": "Magnesium, Mg",
//            "nutrientNumber": "304",
//            "unitName": "MG",
//            "derivationCode": "MC",
//            "derivationDescription": "Manufacturer supplied; Calculated by manufacturer or unknown if analytical or calculated",
//            "derivationId": 47,
//            "value": 241,
//            "foodNutrientSourceId": 7,
//            "foodNutrientSourceCode": "9",
//            "foodNutrientSourceDescription": "Calculated by manufacturer, not adjusted or rounded for NLEA",
//            "rank": 5500,
//            "indentLevel": 1,
//            "foodNutrientId": 1874083,
//            "dataPoints": 0
//        },
//        {
//            "nutrientId": 1091,
//            "nutrientName": "Phosphorus, P",
//            "nutrientNumber": "305",
//            "unitName": "MG",
//            "derivationCode": "MC",
//            "derivationDescription": "Manufacturer supplied; Calculated by manufacturer or unknown if analytical or calculated",
//            "derivationId": 47,
//            "value": 694,
//            "foodNutrientSourceId": 7,
//            "foodNutrientSourceCode": "9",
//            "foodNutrientSourceDescription": "Calculated by manufacturer, not adjusted or rounded for NLEA",
//            "rank": 5600,
//            "indentLevel": 1,
//            "foodNutrientId": 1874084,
//            "dataPoints": 0
//        },
//        {
//            "nutrientId": 1093,
//            "nutrientName": "Sodium, Na",
//            "nutrientNumber": "307",
//            "unitName": "MG",
//            "derivationCode": "MC",
//            "derivationDescription": "Manufacturer supplied; Calculated by manufacturer or unknown if analytical or calculated",
//            "derivationId": 47,
//            "value": 5.0,
//            "foodNutrientSourceId": 7,
//            "foodNutrientSourceCode": "9",
//            "foodNutrientSourceDescription": "Calculated by manufacturer, not adjusted or rounded for NLEA",
//            "rank": 5800,
//            "indentLevel": 1,
//            "foodNutrientId": 1874085,
//            "dataPoints": 0
//        },
//        {
//            "nutrientId": 1079,
//            "nutrientName": "Fiber, total dietary",
//            "nutrientNumber": "291",
//            "unitName": "G",
//            "derivationCode": "MC",
//            "derivationDescription": "Manufacturer supplied; Calculated by manufacturer or unknown if analytical or calculated",
//            "derivationId": 47,
//            "value": 14.3,
//            "foodNutrientSourceId": 7,
//            "foodNutrientSourceCode": "9",
//            "foodNutrientSourceDescription": "Calculated by manufacturer, not adjusted or rounded for NLEA",
//            "rank": 1200,
//            "indentLevel": 3,
//            "foodNutrientId": 1874086,
//            "dataPoints": 0
//        },
//        {
//            "nutrientId": 1187,
//            "nutrientName": "Folate, food",
//            "nutrientNumber": "432",
//            "unitName": "UG",
//            "derivationCode": "MC",
//            "derivationDescription": "Manufacturer supplied; Calculated by manufacturer or unknown if analytical or calculated",
//            "derivationId": 47,
//            "value": 38.0,
//            "foodNutrientSourceId": 7,
//            "foodNutrientSourceCode": "9",
//            "foodNutrientSourceDescription": "Calculated by manufacturer, not adjusted or rounded for NLEA",
//            "rank": 7100,
//            "indentLevel": 1,
//            "foodNutrientId": 1874087,
//            "dataPoints": 0
//        },
//        {
//            "nutrientId": 1062,
//            "nutrientName": "Energy",
//            "nutrientNumber": "268",
//            "unitName": "kJ",
//            "derivationCode": "MC",
//            "derivationDescription": "Manufacturer supplied; Calculated by manufacturer or unknown if analytical or calculated",
//            "derivationId": 47,
//            "value": 1520.0,
//            "foodNutrientSourceId": 7,
//            "foodNutrientSourceCode": "9",
//            "foodNutrientSourceDescription": "Calculated by manufacturer, not adjusted or rounded for NLEA",
//            "rank": 400,
//            "indentLevel": 1,
//            "foodNutrientId": 1874088,
//            "dataPoints": 0
//        },
//        {
//            "nutrientId": 1005,
//            "nutrientName": "Carbohydrate, by difference",
//            "nutrientNumber": "205",
//            "unitName": "G",
//            "derivationCode": "MC",
//            "derivationDescription": "Manufacturer supplied; Calculated by manufacturer or unknown if analytical or calculated",
//            "derivationId": 47,
//            "value": 62.9,
//            "foodNutrientSourceId": 7,
//            "foodNutrientSourceCode": "9",
//            "foodNutrientSourceDescription": "Calculated by manufacturer, not adjusted or rounded for NLEA",
//            "rank": 1110,
//            "indentLevel": 2,
//            "foodNutrientId": 1874089,
//            "dataPoints": 0
//        },
//        {
//            "nutrientId": 1003,
//            "nutrientName": "Protein",
//            "nutrientNumber": "203",
//            "unitName": "G",
//            "derivationCode": "MC",
//            "derivationDescription": "Manufacturer supplied; Calculated by manufacturer or unknown if analytical or calculated",
//            "derivationId": 47,
//            "value": 17.0,
//            "foodNutrientSourceId": 7,
//            "foodNutrientSourceCode": "9",
//            "foodNutrientSourceDescription": "Calculated by manufacturer, not adjusted or rounded for NLEA",
//            "rank": 600,
//            "indentLevel": 1,
//            "foodNutrientId": 1874090,
//            "dataPoints": 0
//        },
//        {
//            "nutrientId": 1110,
//            "nutrientName": "Vitamin D (D2 + D3), International Units",
//            "nutrientNumber": "324",
//            "unitName": "IU",
//            "derivationCode": "Z",
//            "derivationDescription": "Assumed zero (Insignificant amount or not naturally occurring in a food, such as fiber in meat)",
//            "derivationId": 68,
//            "value": 0.0,
//            "foodNutrientSourceId": 5,
//            "foodNutrientSourceCode": "7",
//            "foodNutrientSourceDescription": "Assumed zero",
//            "rank": 8650,
//            "indentLevel": 1,
//            "foodNutrientId": 1874091,
//            "dataPoints": 0
//        },
//        {
//            "nutrientId": 1190,
//            "nutrientName": "Folate, DFE",
//            "nutrientNumber": "435",
//            "unitName": "UG",
//            "derivationCode": "NC",
//            "derivationDescription": "Calculated",
//            "derivationId": 49,
//            "value": 38.0,
//            "foodNutrientSourceId": 2,
//            "foodNutrientSourceCode": "4",
//            "foodNutrientSourceDescription": "Calculated or imputed",
//            "rank": 7200,
//            "indentLevel": 1,
//            "foodNutrientId": 1874092,
//            "dataPoints": 0
//        },
//        {
//            "nutrientId": 1114,
//            "nutrientName": "Vitamin D (D2 + D3)",
//            "nutrientNumber": "328",
//            "unitName": "UG",
//            "derivationCode": "Z",
//            "derivationDescription": "Assumed zero (Insignificant amount or not naturally occurring in a food, such as fiber in meat)",
//            "derivationId": 68,
//            "value": 0.0,
//            "foodNutrientSourceId": 5,
//            "foodNutrientSourceCode": "7",
//            "foodNutrientSourceDescription": "Assumed zero",
//            "rank": 8700,
//            "indentLevel": 1,
//            "foodNutrientId": 1874093,
//            "dataPoints": 0
//        },
//        {
//            "nutrientId": 1186,
//            "nutrientName": "Folic acid",
//            "nutrientNumber": "431",
//            "unitName": "UG",
//            "derivationCode": "Z",
//            "derivationDescription": "Assumed zero (Insignificant amount or not naturally occurring in a food, such as fiber in meat)",
//            "derivationId": 68,
//            "value": 0.0,
//            "foodNutrientSourceId": 5,
//            "foodNutrientSourceCode": "7",
//            "foodNutrientSourceDescription": "Assumed zero",
//            "rank": 7000,
//            "indentLevel": 0,
//            "foodNutrientId": 1874094,
//            "dataPoints": 0
//        }
//    ],
//    "finalFoodInputFoods": [],
//    "foodMeasures": [],
//    "foodAttributes": [],
//    "foodAttributeTypes": [],
//    "foodVersionIds": []
//},
